// <auto-generated />
using System;
using BillFlow.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BillFlow.Migrations
{
    [DbContext(typeof(BillFlowDbContext))]
    [Migration("20260411000001_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("BillFlow.Models.AppSettings", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Address")
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<string>("BusinessName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT")
                    .HasDefaultValue("My Printing Business");

                b.Property<decimal>("DefaultCreditLimit")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("REAL")
                    .HasDefaultValue(10000m);

                b.Property<string>("InvoicePrefix")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("TEXT")
                    .HasDefaultValue("INV");

                b.Property<int>("LastInvoiceNumber")
                    .HasColumnType("INTEGER");

                b.Property<string>("OwnerName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<string>("Phone")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("TEXT");

                b.Property<decimal>("RatePerSqFt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("REAL")
                    .HasDefaultValue(50m);

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Settings");

                b.HasData(
                    new
                    {
                        Id = 1,
                        BusinessName = "My Printing Business",
                        DefaultCreditLimit = 10000m,
                        InvoicePrefix = "INV",
                        LastInvoiceNumber = 0,
                        OwnerName = "",
                        Phone = "",
                        RatePerSqFt = 50m,
                        UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                    });
            });

            modelBuilder.Entity("BillFlow.Models.Customer", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Address")
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("CustomerCode")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<decimal>("CreditLimit")
                    .HasColumnType("REAL");

                b.Property<DateTime?>("LastPaymentDate")
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<string>("Phone")
                    .HasMaxLength(20)
                    .HasColumnType("TEXT");

                b.Property<decimal>("TotalCredit")
                    .HasColumnType("REAL");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("CustomerCode")
                    .IsUnique();

                b.HasIndex("Name");

                b.HasIndex("Phone");

                b.ToTable("Customers");
            });

            modelBuilder.Entity("BillFlow.Models.DailyScheduleItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("Priority")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("ScheduleDate")
                    .HasColumnType("TEXT");

                b.Property<int>("Status")
                    .HasColumnType("INTEGER");

                b.Property<int>("WorkOrderId")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("ScheduleDate");

                b.HasIndex("WorkOrderId");

                b.ToTable("DailyScheduleItems");
            });

            modelBuilder.Entity("BillFlow.Models.KhataEntry", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<decimal>("Amount")
                    .HasColumnType("REAL");

                b.Property<decimal>("Balance")
                    .HasColumnType("REAL");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<int>("CustomerId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Notes")
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("TransactionDate")
                    .HasColumnType("TEXT");

                b.Property<int>("Type")
                    .HasColumnType("INTEGER");

                b.Property<int?>("WorkOrderId")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("CustomerId");

                b.HasIndex("TransactionDate");

                b.HasIndex("WorkOrderId");

                b.ToTable("KhataEntries");
            });

            modelBuilder.Entity("BillFlow.Models.LineItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<decimal>("Area")
                    .HasColumnType("REAL");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<decimal>("Height")
                    .HasColumnType("REAL");

                b.Property<int>("Quantity")
                    .HasColumnType("INTEGER");

                b.Property<decimal>("Rate")
                    .HasColumnType("REAL");

                b.Property<decimal>("Total")
                    .HasColumnType("REAL");

                b.Property<int>("WorkOrderId")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("WorkOrderId");

                b.ToTable("LineItems");
            });

            modelBuilder.Entity("BillFlow.Models.WorkOrder", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<decimal>("AmountPaid")
                    .HasColumnType("REAL");

                b.Property<int>("CustomerId")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<decimal>("GrandTotal")
                    .HasColumnType("REAL");

                b.Property<string>("Notes")
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<string>("OrderCode")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("OrderDate")
                    .HasColumnType("TEXT");

                b.Property<decimal>("PastBill")
                    .HasColumnType("REAL");

                b.Property<int>("PaymentStatus")
                    .HasColumnType("INTEGER");

                b.Property<decimal>("PendingAmount")
                    .HasColumnType("REAL");

                b.Property<DateTime?>("ScheduledDate")
                    .HasColumnType("TEXT");

                b.Property<decimal>("TotalAmount")
                    .HasColumnType("REAL");

                b.Property<decimal>("TotalArea")
                    .HasColumnType("REAL");

                b.Property<int>("WorkStatus")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("CustomerId");

                b.HasIndex("OrderCode")
                    .IsUnique();

                b.HasIndex("PaymentStatus");

                b.HasIndex("ScheduledDate");

                b.HasIndex("WorkStatus");

                b.ToTable("WorkOrders");
            });

            modelBuilder.Entity("BillFlow.Models.DailyScheduleItem", b =>
            {
                b.HasOne("BillFlow.Models.WorkOrder", "WorkOrder")
                    .WithMany()
                    .HasForeignKey("WorkOrderId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("WorkOrder");
            });

            modelBuilder.Entity("BillFlow.Models.KhataEntry", b =>
            {
                b.HasOne("BillFlow.Models.Customer", "Customer")
                    .WithMany("KhataEntries")
                    .HasForeignKey("CustomerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("BillFlow.Models.WorkOrder", "WorkOrder")
                    .WithMany()
                    .HasForeignKey("WorkOrderId");

                b.Navigation("Customer");

                b.Navigation("WorkOrder");
            });

            modelBuilder.Entity("BillFlow.Models.LineItem", b =>
            {
                b.HasOne("BillFlow.Models.WorkOrder", "WorkOrder")
                    .WithMany("LineItems")
                    .HasForeignKey("WorkOrderId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("WorkOrder");
            });

            modelBuilder.Entity("BillFlow.Models.WorkOrder", b =>
            {
                b.HasOne("BillFlow.Models.Customer", "Customer")
                    .WithMany("WorkOrders")
                    .HasForeignKey("CustomerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Customer");
            });

            modelBuilder.Entity("BillFlow.Models.Customer", b =>
            {
                b.Navigation("KhataEntries");

                b.Navigation("WorkOrders");
            });

            modelBuilder.Entity("BillFlow.Models.WorkOrder", b =>
            {
                b.Navigation("LineItems");
            });
#pragma warning restore 612, 618
        }
    }
}
